kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pgmonitor
spec:
  host: pgmonitor-pgmonitor.apps.ocp4-bpace.ocpdemos.crunchydata.com
  to:
    kind: Service
    name: crunchy-grafana
    weight: 100
  port:
    targetPort: grafana
  wildcardPolicy: None
