apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pgbackrest-pgnow
  finalizers:
    - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: pgbackrest-pgnow-repo
  generateBucketName: pgbackrest-pgnow
  objectBucketName: obc-default-pgbackrest-pgnow
  storageClassName: openshift-storage.noobaa.io